#ifndef K9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
#define K9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
class QWidget;

void OPEN_K9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH ( int p_kitapcik_mi, QWidget * parent );

#endif // K9_KUL_KITAPCIGI_VE_YARDIM_SAYFASI_BATCH_OPEN_H
